// GENERATED FILE. Do not edit.
// Produced by scripts/generate-route-manifest.ts from src/routeTree.gen.ts.
// Every URL this deployment serves, used as the single source of truth for
// canary / smoke monitoring (see src/lib/canary-routes.ts).

export const ROUTE_MANIFEST = [
  "/",
  "/$city",
  "/$city/",
  "/$city/pricing",
  "/.lovable/oauth/consent",
  "/.mcp/invoke-tool/$tool",
  "/.mcp/list-tools",
  "/.well-known/oauth-protected-resource",
  "/admin/canary",
  "/admin/crm",
  "/admin/crm/$",
  "/admin/lead-sources",
  "/admin/lead-sync",
  "/admin/leads",
  "/admin/not-found",
  "/admin/pool-map",
  "/admin/reviews",
  "/admin/webhook-health",
  "/api/public/events",
  "/api/public/health",
  "/api/public/hooks/canary",
  "/api/public/hooks/crm-appointment-status",
  "/api/public/hooks/crm-lead-update",
  "/api/public/hooks/crm-payment-status",
  "/api/public/hooks/failure-rate-watch",
  "/api/public/hooks/health-watch",
  "/api/public/hooks/low-stock-watch",
  "/api/public/hooks/smoke-alert",
  "/api/public/hooks/visit-reminders",
  "/api/public/hooks/webhook-watch",
  "/api/public/leads",
  "/api/public/twilio/contract-sms-status",
  "/api/public/twilio/inbound",
  "/app",
  "/app/$",
  "/b",
  "/book",
  "/booking",
  "/free-inspection",
  "/frisco",
  "/leave-a-review",
  "/lovable/email/auth/preview",
  "/lovable/email/auth/webhook",
  "/mcp",
  "/our-work",
  "/plano",
  "/pool-cleaning-frisco",
  "/pool-cleaning-frisco-tx",
  "/pool-cleaning-plano",
  "/portal",
  "/privacy",
  "/privacy-policy",
  "/quote/$token",
  "/refer",
  "/request-inspection",
  "/review/$token",
  "/schedule",
  "/schedule-qr",
  "/services",
  "/sign/$token",
  "/terms",
  "/terms-and-conditions",
  "/thank-you",
  "/weekly-pool-service",
] as const;

/** Routes whose loader intentionally responds with a 301/302. */
export const REDIRECT_ROUTES = [
  "/.lovable/oauth/consent",
  "/b",
  "/book",
  "/booking",
  "/free-inspection",
  "/request-inspection",
] as const;

export type DeployedRoute = (typeof ROUTE_MANIFEST)[number];
