project_id = "yabkgfqrbbvgipsobond"

[functions.create-checkout]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
