/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyPoolServiceRouteImport } from './routes/weekly-pool-service'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestInspectionRouteImport } from './routes/request-inspection'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PoolCleaningPlanoRouteImport } from './routes/pool-cleaning-plano'
import { Route as PoolCleaningFriscoTxRouteImport } from './routes/pool-cleaning-frisco-tx'
import { Route as PoolCleaningFriscoRouteImport } from './routes/pool-cleaning-frisco'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FriscoRouteImport } from './routes/frisco'
import { Route as FreeInspectionRouteImport } from './routes/free-inspection'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BookRouteImport } from './routes/book'
import { Route as BRouteImport } from './routes/b'
import { Route as CityRouteImport } from './routes/$city'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign/$token'
import { Route as ReviewTokenRouteImport } from './routes/review/$token'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as AdminWebhookHealthRouteImport } from './routes/admin/webhook-health'
import { Route as AdminLeadSyncRouteImport } from './routes/admin/lead-sync'
import { Route as AdminLeadSourcesRouteImport } from './routes/admin/lead-sources'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api/public/twilio/inbound'
import { Route as ApiPublicTwilioContractSmsStatusRouteImport } from './routes/api/public/twilio/contract-sms-status'
import { Route as ApiPublicHooksWebhookWatchRouteImport } from './routes/api/public/hooks/webhook-watch'
import { Route as ApiPublicHooksVisitRemindersRouteImport } from './routes/api/public/hooks/visit-reminders'
import { Route as ApiPublicHooksLowStockWatchRouteImport } from './routes/api/public/hooks/low-stock-watch'
import { Route as ApiPublicHooksHealthWatchRouteImport } from './routes/api/public/hooks/health-watch'
import { Route as ApiPublicHooksFailureRateWatchRouteImport } from './routes/api/public/hooks/failure-rate-watch'
import { Route as ApiPublicHooksCrmPaymentStatusRouteImport } from './routes/api/public/hooks/crm-payment-status'
import { Route as ApiPublicHooksCrmLeadUpdateRouteImport } from './routes/api/public/hooks/crm-lead-update'
import { Route as ApiPublicHooksCrmAppointmentStatusRouteImport } from './routes/api/public/hooks/crm-appointment-status'
import { Route as ApiPublicHooksCanaryRouteImport } from './routes/api/public/hooks/canary'

const WeeklyPoolServiceRoute = WeeklyPoolServiceRouteImport.update({
  id: '/weekly-pool-service',
  path: '/weekly-pool-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestInspectionRoute = RequestInspectionRouteImport.update({
  id: '/request-inspection',
  path: '/request-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolCleaningPlanoRoute = PoolCleaningPlanoRouteImport.update({
  id: '/pool-cleaning-plano',
  path: '/pool-cleaning-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolCleaningFriscoTxRoute = PoolCleaningFriscoTxRouteImport.update({
  id: '/pool-cleaning-frisco-tx',
  path: '/pool-cleaning-frisco-tx',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolCleaningFriscoRoute = PoolCleaningFriscoRouteImport.update({
  id: '/pool-cleaning-frisco',
  path: '/pool-cleaning-frisco',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FriscoRoute = FriscoRouteImport.update({
  id: '/frisco',
  path: '/frisco',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeInspectionRoute = FreeInspectionRouteImport.update({
  id: '/free-inspection',
  path: '/free-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BRoute = BRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhookHealthRoute = AdminWebhookHealthRouteImport.update({
  id: '/admin/webhook-health',
  path: '/admin/webhook-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadSyncRoute = AdminLeadSyncRouteImport.update({
  id: '/admin/lead-sync',
  path: '/admin/lead-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadSourcesRoute = AdminLeadSourcesRouteImport.update({
  id: '/admin/lead-sources',
  path: '/admin/lead-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio/inbound',
  path: '/api/public/twilio/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioContractSmsStatusRoute =
  ApiPublicTwilioContractSmsStatusRouteImport.update({
    id: '/api/public/twilio/contract-sms-status',
    path: '/api/public/twilio/contract-sms-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWebhookWatchRoute =
  ApiPublicHooksWebhookWatchRouteImport.update({
    id: '/api/public/hooks/webhook-watch',
    path: '/api/public/hooks/webhook-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVisitRemindersRoute =
  ApiPublicHooksVisitRemindersRouteImport.update({
    id: '/api/public/hooks/visit-reminders',
    path: '/api/public/hooks/visit-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLowStockWatchRoute =
  ApiPublicHooksLowStockWatchRouteImport.update({
    id: '/api/public/hooks/low-stock-watch',
    path: '/api/public/hooks/low-stock-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthWatchRoute =
  ApiPublicHooksHealthWatchRouteImport.update({
    id: '/api/public/hooks/health-watch',
    path: '/api/public/hooks/health-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFailureRateWatchRoute =
  ApiPublicHooksFailureRateWatchRouteImport.update({
    id: '/api/public/hooks/failure-rate-watch',
    path: '/api/public/hooks/failure-rate-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmPaymentStatusRoute =
  ApiPublicHooksCrmPaymentStatusRouteImport.update({
    id: '/api/public/hooks/crm-payment-status',
    path: '/api/public/hooks/crm-payment-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmLeadUpdateRoute =
  ApiPublicHooksCrmLeadUpdateRouteImport.update({
    id: '/api/public/hooks/crm-lead-update',
    path: '/api/public/hooks/crm-lead-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmAppointmentStatusRoute =
  ApiPublicHooksCrmAppointmentStatusRouteImport.update({
    id: '/api/public/hooks/crm-appointment-status',
    path: '/api/public/hooks/crm-appointment-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCanaryRoute = ApiPublicHooksCanaryRouteImport.update({
  id: '/api/public/hooks/canary',
  path: '/api/public/hooks/canary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$city': typeof CityRoute
  '/b': typeof BRoute
  '/book': typeof BookRoute
  '/booking': typeof BookingRoute
  '/free-inspection': typeof FreeInspectionRoute
  '/frisco': typeof FriscoRoute
  '/mcp': typeof McpRoute
  '/plano': typeof PlanoRoute
  '/pool-cleaning-frisco': typeof PoolCleaningFriscoRoute
  '/pool-cleaning-frisco-tx': typeof PoolCleaningFriscoTxRoute
  '/pool-cleaning-plano': typeof PoolCleaningPlanoRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-inspection': typeof RequestInspectionRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/weekly-pool-service': typeof WeeklyPoolServiceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/lead-sources': typeof AdminLeadSourcesRoute
  '/admin/lead-sync': typeof AdminLeadSyncRoute
  '/admin/webhook-health': typeof AdminWebhookHealthRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/canary': typeof ApiPublicHooksCanaryRoute
  '/api/public/hooks/crm-appointment-status': typeof ApiPublicHooksCrmAppointmentStatusRoute
  '/api/public/hooks/crm-lead-update': typeof ApiPublicHooksCrmLeadUpdateRoute
  '/api/public/hooks/crm-payment-status': typeof ApiPublicHooksCrmPaymentStatusRoute
  '/api/public/hooks/failure-rate-watch': typeof ApiPublicHooksFailureRateWatchRoute
  '/api/public/hooks/health-watch': typeof ApiPublicHooksHealthWatchRoute
  '/api/public/hooks/low-stock-watch': typeof ApiPublicHooksLowStockWatchRoute
  '/api/public/hooks/visit-reminders': typeof ApiPublicHooksVisitRemindersRoute
  '/api/public/hooks/webhook-watch': typeof ApiPublicHooksWebhookWatchRoute
  '/api/public/twilio/contract-sms-status': typeof ApiPublicTwilioContractSmsStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$city': typeof CityRoute
  '/b': typeof BRoute
  '/book': typeof BookRoute
  '/booking': typeof BookingRoute
  '/free-inspection': typeof FreeInspectionRoute
  '/frisco': typeof FriscoRoute
  '/mcp': typeof McpRoute
  '/plano': typeof PlanoRoute
  '/pool-cleaning-frisco': typeof PoolCleaningFriscoRoute
  '/pool-cleaning-frisco-tx': typeof PoolCleaningFriscoTxRoute
  '/pool-cleaning-plano': typeof PoolCleaningPlanoRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-inspection': typeof RequestInspectionRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/weekly-pool-service': typeof WeeklyPoolServiceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/lead-sources': typeof AdminLeadSourcesRoute
  '/admin/lead-sync': typeof AdminLeadSyncRoute
  '/admin/webhook-health': typeof AdminWebhookHealthRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/canary': typeof ApiPublicHooksCanaryRoute
  '/api/public/hooks/crm-appointment-status': typeof ApiPublicHooksCrmAppointmentStatusRoute
  '/api/public/hooks/crm-lead-update': typeof ApiPublicHooksCrmLeadUpdateRoute
  '/api/public/hooks/crm-payment-status': typeof ApiPublicHooksCrmPaymentStatusRoute
  '/api/public/hooks/failure-rate-watch': typeof ApiPublicHooksFailureRateWatchRoute
  '/api/public/hooks/health-watch': typeof ApiPublicHooksHealthWatchRoute
  '/api/public/hooks/low-stock-watch': typeof ApiPublicHooksLowStockWatchRoute
  '/api/public/hooks/visit-reminders': typeof ApiPublicHooksVisitRemindersRoute
  '/api/public/hooks/webhook-watch': typeof ApiPublicHooksWebhookWatchRoute
  '/api/public/twilio/contract-sms-status': typeof ApiPublicTwilioContractSmsStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$city': typeof CityRoute
  '/b': typeof BRoute
  '/book': typeof BookRoute
  '/booking': typeof BookingRoute
  '/free-inspection': typeof FreeInspectionRoute
  '/frisco': typeof FriscoRoute
  '/mcp': typeof McpRoute
  '/plano': typeof PlanoRoute
  '/pool-cleaning-frisco': typeof PoolCleaningFriscoRoute
  '/pool-cleaning-frisco-tx': typeof PoolCleaningFriscoTxRoute
  '/pool-cleaning-plano': typeof PoolCleaningPlanoRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-inspection': typeof RequestInspectionRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/weekly-pool-service': typeof WeeklyPoolServiceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/lead-sources': typeof AdminLeadSourcesRoute
  '/admin/lead-sync': typeof AdminLeadSyncRoute
  '/admin/webhook-health': typeof AdminWebhookHealthRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/canary': typeof ApiPublicHooksCanaryRoute
  '/api/public/hooks/crm-appointment-status': typeof ApiPublicHooksCrmAppointmentStatusRoute
  '/api/public/hooks/crm-lead-update': typeof ApiPublicHooksCrmLeadUpdateRoute
  '/api/public/hooks/crm-payment-status': typeof ApiPublicHooksCrmPaymentStatusRoute
  '/api/public/hooks/failure-rate-watch': typeof ApiPublicHooksFailureRateWatchRoute
  '/api/public/hooks/health-watch': typeof ApiPublicHooksHealthWatchRoute
  '/api/public/hooks/low-stock-watch': typeof ApiPublicHooksLowStockWatchRoute
  '/api/public/hooks/visit-reminders': typeof ApiPublicHooksVisitRemindersRoute
  '/api/public/hooks/webhook-watch': typeof ApiPublicHooksWebhookWatchRoute
  '/api/public/twilio/contract-sms-status': typeof ApiPublicTwilioContractSmsStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$city'
    | '/b'
    | '/book'
    | '/booking'
    | '/free-inspection'
    | '/frisco'
    | '/mcp'
    | '/plano'
    | '/pool-cleaning-frisco'
    | '/pool-cleaning-frisco-tx'
    | '/pool-cleaning-plano'
    | '/portal'
    | '/privacy'
    | '/privacy-policy'
    | '/request-inspection'
    | '/services'
    | '/terms'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/weekly-pool-service'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/lead-sources'
    | '/admin/lead-sync'
    | '/admin/webhook-health'
    | '/quote/$token'
    | '/review/$token'
    | '/sign/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/events'
    | '/api/public/health'
    | '/api/public/leads'
    | '/api/public/hooks/canary'
    | '/api/public/hooks/crm-appointment-status'
    | '/api/public/hooks/crm-lead-update'
    | '/api/public/hooks/crm-payment-status'
    | '/api/public/hooks/failure-rate-watch'
    | '/api/public/hooks/health-watch'
    | '/api/public/hooks/low-stock-watch'
    | '/api/public/hooks/visit-reminders'
    | '/api/public/hooks/webhook-watch'
    | '/api/public/twilio/contract-sms-status'
    | '/api/public/twilio/inbound'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$city'
    | '/b'
    | '/book'
    | '/booking'
    | '/free-inspection'
    | '/frisco'
    | '/mcp'
    | '/plano'
    | '/pool-cleaning-frisco'
    | '/pool-cleaning-frisco-tx'
    | '/pool-cleaning-plano'
    | '/portal'
    | '/privacy'
    | '/privacy-policy'
    | '/request-inspection'
    | '/services'
    | '/terms'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/weekly-pool-service'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/lead-sources'
    | '/admin/lead-sync'
    | '/admin/webhook-health'
    | '/quote/$token'
    | '/review/$token'
    | '/sign/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/events'
    | '/api/public/health'
    | '/api/public/leads'
    | '/api/public/hooks/canary'
    | '/api/public/hooks/crm-appointment-status'
    | '/api/public/hooks/crm-lead-update'
    | '/api/public/hooks/crm-payment-status'
    | '/api/public/hooks/failure-rate-watch'
    | '/api/public/hooks/health-watch'
    | '/api/public/hooks/low-stock-watch'
    | '/api/public/hooks/visit-reminders'
    | '/api/public/hooks/webhook-watch'
    | '/api/public/twilio/contract-sms-status'
    | '/api/public/twilio/inbound'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/$city'
    | '/b'
    | '/book'
    | '/booking'
    | '/free-inspection'
    | '/frisco'
    | '/mcp'
    | '/plano'
    | '/pool-cleaning-frisco'
    | '/pool-cleaning-frisco-tx'
    | '/pool-cleaning-plano'
    | '/portal'
    | '/privacy'
    | '/privacy-policy'
    | '/request-inspection'
    | '/services'
    | '/terms'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/weekly-pool-service'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/lead-sources'
    | '/admin/lead-sync'
    | '/admin/webhook-health'
    | '/quote/$token'
    | '/review/$token'
    | '/sign/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/events'
    | '/api/public/health'
    | '/api/public/leads'
    | '/api/public/hooks/canary'
    | '/api/public/hooks/crm-appointment-status'
    | '/api/public/hooks/crm-lead-update'
    | '/api/public/hooks/crm-payment-status'
    | '/api/public/hooks/failure-rate-watch'
    | '/api/public/hooks/health-watch'
    | '/api/public/hooks/low-stock-watch'
    | '/api/public/hooks/visit-reminders'
    | '/api/public/hooks/webhook-watch'
    | '/api/public/twilio/contract-sms-status'
    | '/api/public/twilio/inbound'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRoute
  BRoute: typeof BRoute
  BookRoute: typeof BookRoute
  BookingRoute: typeof BookingRoute
  FreeInspectionRoute: typeof FreeInspectionRoute
  FriscoRoute: typeof FriscoRoute
  McpRoute: typeof McpRoute
  PlanoRoute: typeof PlanoRoute
  PoolCleaningFriscoRoute: typeof PoolCleaningFriscoRoute
  PoolCleaningFriscoTxRoute: typeof PoolCleaningFriscoTxRoute
  PoolCleaningPlanoRoute: typeof PoolCleaningPlanoRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RequestInspectionRoute: typeof RequestInspectionRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ThankYouRoute: typeof ThankYouRoute
  WeeklyPoolServiceRoute: typeof WeeklyPoolServiceRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLeadSourcesRoute: typeof AdminLeadSourcesRoute
  AdminLeadSyncRoute: typeof AdminLeadSyncRoute
  AdminWebhookHealthRoute: typeof AdminWebhookHealthRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicHooksCanaryRoute: typeof ApiPublicHooksCanaryRoute
  ApiPublicHooksCrmAppointmentStatusRoute: typeof ApiPublicHooksCrmAppointmentStatusRoute
  ApiPublicHooksCrmLeadUpdateRoute: typeof ApiPublicHooksCrmLeadUpdateRoute
  ApiPublicHooksCrmPaymentStatusRoute: typeof ApiPublicHooksCrmPaymentStatusRoute
  ApiPublicHooksFailureRateWatchRoute: typeof ApiPublicHooksFailureRateWatchRoute
  ApiPublicHooksHealthWatchRoute: typeof ApiPublicHooksHealthWatchRoute
  ApiPublicHooksLowStockWatchRoute: typeof ApiPublicHooksLowStockWatchRoute
  ApiPublicHooksVisitRemindersRoute: typeof ApiPublicHooksVisitRemindersRoute
  ApiPublicHooksWebhookWatchRoute: typeof ApiPublicHooksWebhookWatchRoute
  ApiPublicTwilioContractSmsStatusRoute: typeof ApiPublicTwilioContractSmsStatusRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-pool-service': {
      id: '/weekly-pool-service'
      path: '/weekly-pool-service'
      fullPath: '/weekly-pool-service'
      preLoaderRoute: typeof WeeklyPoolServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-inspection': {
      id: '/request-inspection'
      path: '/request-inspection'
      fullPath: '/request-inspection'
      preLoaderRoute: typeof RequestInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-cleaning-plano': {
      id: '/pool-cleaning-plano'
      path: '/pool-cleaning-plano'
      fullPath: '/pool-cleaning-plano'
      preLoaderRoute: typeof PoolCleaningPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-cleaning-frisco-tx': {
      id: '/pool-cleaning-frisco-tx'
      path: '/pool-cleaning-frisco-tx'
      fullPath: '/pool-cleaning-frisco-tx'
      preLoaderRoute: typeof PoolCleaningFriscoTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-cleaning-frisco': {
      id: '/pool-cleaning-frisco'
      path: '/pool-cleaning-frisco'
      fullPath: '/pool-cleaning-frisco'
      preLoaderRoute: typeof PoolCleaningFriscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frisco': {
      id: '/frisco'
      path: '/frisco'
      fullPath: '/frisco'
      preLoaderRoute: typeof FriscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-inspection': {
      id: '/free-inspection'
      path: '/free-inspection'
      fullPath: '/free-inspection'
      preLoaderRoute: typeof FreeInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city': {
      id: '/$city'
      path: '/$city'
      fullPath: '/$city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhook-health': {
      id: '/admin/webhook-health'
      path: '/admin/webhook-health'
      fullPath: '/admin/webhook-health'
      preLoaderRoute: typeof AdminWebhookHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lead-sync': {
      id: '/admin/lead-sync'
      path: '/admin/lead-sync'
      fullPath: '/admin/lead-sync'
      preLoaderRoute: typeof AdminLeadSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lead-sources': {
      id: '/admin/lead-sources'
      path: '/admin/lead-sources'
      fullPath: '/admin/lead-sources'
      preLoaderRoute: typeof AdminLeadSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/inbound': {
      id: '/api/public/twilio/inbound'
      path: '/api/public/twilio/inbound'
      fullPath: '/api/public/twilio/inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/contract-sms-status': {
      id: '/api/public/twilio/contract-sms-status'
      path: '/api/public/twilio/contract-sms-status'
      fullPath: '/api/public/twilio/contract-sms-status'
      preLoaderRoute: typeof ApiPublicTwilioContractSmsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/webhook-watch': {
      id: '/api/public/hooks/webhook-watch'
      path: '/api/public/hooks/webhook-watch'
      fullPath: '/api/public/hooks/webhook-watch'
      preLoaderRoute: typeof ApiPublicHooksWebhookWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/visit-reminders': {
      id: '/api/public/hooks/visit-reminders'
      path: '/api/public/hooks/visit-reminders'
      fullPath: '/api/public/hooks/visit-reminders'
      preLoaderRoute: typeof ApiPublicHooksVisitRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/low-stock-watch': {
      id: '/api/public/hooks/low-stock-watch'
      path: '/api/public/hooks/low-stock-watch'
      fullPath: '/api/public/hooks/low-stock-watch'
      preLoaderRoute: typeof ApiPublicHooksLowStockWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health-watch': {
      id: '/api/public/hooks/health-watch'
      path: '/api/public/hooks/health-watch'
      fullPath: '/api/public/hooks/health-watch'
      preLoaderRoute: typeof ApiPublicHooksHealthWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/failure-rate-watch': {
      id: '/api/public/hooks/failure-rate-watch'
      path: '/api/public/hooks/failure-rate-watch'
      fullPath: '/api/public/hooks/failure-rate-watch'
      preLoaderRoute: typeof ApiPublicHooksFailureRateWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-payment-status': {
      id: '/api/public/hooks/crm-payment-status'
      path: '/api/public/hooks/crm-payment-status'
      fullPath: '/api/public/hooks/crm-payment-status'
      preLoaderRoute: typeof ApiPublicHooksCrmPaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-lead-update': {
      id: '/api/public/hooks/crm-lead-update'
      path: '/api/public/hooks/crm-lead-update'
      fullPath: '/api/public/hooks/crm-lead-update'
      preLoaderRoute: typeof ApiPublicHooksCrmLeadUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-appointment-status': {
      id: '/api/public/hooks/crm-appointment-status'
      path: '/api/public/hooks/crm-appointment-status'
      fullPath: '/api/public/hooks/crm-appointment-status'
      preLoaderRoute: typeof ApiPublicHooksCrmAppointmentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/canary': {
      id: '/api/public/hooks/canary'
      path: '/api/public/hooks/canary'
      fullPath: '/api/public/hooks/canary'
      preLoaderRoute: typeof ApiPublicHooksCanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRoute,
  BRoute: BRoute,
  BookRoute: BookRoute,
  BookingRoute: BookingRoute,
  FreeInspectionRoute: FreeInspectionRoute,
  FriscoRoute: FriscoRoute,
  McpRoute: McpRoute,
  PlanoRoute: PlanoRoute,
  PoolCleaningFriscoRoute: PoolCleaningFriscoRoute,
  PoolCleaningFriscoTxRoute: PoolCleaningFriscoTxRoute,
  PoolCleaningPlanoRoute: PoolCleaningPlanoRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RequestInspectionRoute: RequestInspectionRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ThankYouRoute: ThankYouRoute,
  WeeklyPoolServiceRoute: WeeklyPoolServiceRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLeadSourcesRoute: AdminLeadSourcesRoute,
  AdminLeadSyncRoute: AdminLeadSyncRoute,
  AdminWebhookHealthRoute: AdminWebhookHealthRoute,
  QuoteTokenRoute: QuoteTokenRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  SignTokenRoute: SignTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicHooksCanaryRoute: ApiPublicHooksCanaryRoute,
  ApiPublicHooksCrmAppointmentStatusRoute:
    ApiPublicHooksCrmAppointmentStatusRoute,
  ApiPublicHooksCrmLeadUpdateRoute: ApiPublicHooksCrmLeadUpdateRoute,
  ApiPublicHooksCrmPaymentStatusRoute: ApiPublicHooksCrmPaymentStatusRoute,
  ApiPublicHooksFailureRateWatchRoute: ApiPublicHooksFailureRateWatchRoute,
  ApiPublicHooksHealthWatchRoute: ApiPublicHooksHealthWatchRoute,
  ApiPublicHooksLowStockWatchRoute: ApiPublicHooksLowStockWatchRoute,
  ApiPublicHooksVisitRemindersRoute: ApiPublicHooksVisitRemindersRoute,
  ApiPublicHooksWebhookWatchRoute: ApiPublicHooksWebhookWatchRoute,
  ApiPublicTwilioContractSmsStatusRoute: ApiPublicTwilioContractSmsStatusRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
