/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmRouteImport } from './routes/_crm'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FreeInspectionRouteImport } from './routes/free-inspection'
import { Route as PoolCleaningFriscoTxRouteImport } from './routes/pool-cleaning-frisco-tx'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RequestInspectionRouteImport } from './routes/request-inspection'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminCleaningRouteImport } from './routes/admin/cleaning'
import { Route as AdminDesignsRouteImport } from './routes/admin/designs'
import { Route as AdminStoreRouteImport } from './routes/admin/store'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CrmSplatRouteImport } from './routes/crm/$'
import { Route as ReviewTokenRouteImport } from './routes/review/$token'
import { Route as AdminCrmAppRouteImport } from './routes/admin/crm/app'
import { Route as AdminCrmLegacyRouteImport } from './routes/admin/crm/legacy'
import { Route as AdminCrmLoginRouteImport } from './routes/admin/crm/login'
import { Route as CrmAdminCrmIndexRouteImport } from './routes/_crm/admin/crm/index'
import { Route as CrmAdminCrmAlertsRouteImport } from './routes/_crm/admin/crm/alerts'
import { Route as CrmAdminCrmBreakEvenRouteImport } from './routes/_crm/admin/crm/break-even'
import { Route as CrmAdminCrmConnectRouteImport } from './routes/_crm/admin/crm/connect'
import { Route as CrmAdminCrmEmailRouteImport } from './routes/_crm/admin/crm/email'
import { Route as CrmAdminCrmFinanceRouteImport } from './routes/_crm/admin/crm/finance'
import { Route as CrmAdminCrmInventoryRouteImport } from './routes/_crm/admin/crm/inventory'
import { Route as CrmAdminCrmJobsRouteImport } from './routes/_crm/admin/crm/jobs'
import { Route as CrmAdminCrmMarginRouteImport } from './routes/_crm/admin/crm/margin'
import { Route as CrmAdminCrmPayPerPoolRouteImport } from './routes/_crm/admin/crm/pay-per-pool'
import { Route as CrmAdminCrmPipelineRouteImport } from './routes/_crm/admin/crm/pipeline'
import { Route as CrmAdminCrmPricingMatrixRouteImport } from './routes/_crm/admin/crm/pricing-matrix'
import { Route as CrmAdminCrmProductsRouteImport } from './routes/_crm/admin/crm/products'
import { Route as CrmAdminCrmQcReviewRouteImport } from './routes/_crm/admin/crm/qc-review'
import { Route as CrmAdminCrmReportsRouteImport } from './routes/_crm/admin/crm/reports'
import { Route as CrmAdminCrmRevenueGrowthRouteImport } from './routes/_crm/admin/crm/revenue-growth'
import { Route as CrmAdminCrmReviewsRouteImport } from './routes/_crm/admin/crm/reviews'
import { Route as CrmAdminCrmScorecardRouteImport } from './routes/_crm/admin/crm/scorecard'
import { Route as CrmAdminCrmSecurityRouteImport } from './routes/_crm/admin/crm/security'
import { Route as CrmAdminCrmServicePlansRouteImport } from './routes/_crm/admin/crm/service-plans'
import { Route as CrmAdminCrmSettingsRouteImport } from './routes/_crm/admin/crm/settings'
import { Route as CrmAdminCrmTechniciansRouteImport } from './routes/_crm/admin/crm/technicians'
import { Route as CrmAdminCrmTrucksRouteImport } from './routes/_crm/admin/crm/trucks'
import { Route as CrmAdminCrmWaterLabRouteImport } from './routes/_crm/admin/crm/water-lab'
import { Route as CrmAdminCrmCustomersIndexRouteImport } from './routes/_crm/admin/crm/customers/index'
import { Route as CrmAdminCrmCustomersIdRouteImport } from './routes/_crm/admin/crm/customers/$id'
import { Route as CrmAdminCrmProjectsIndexRouteImport } from './routes/_crm/admin/crm/projects/index'
import { Route as CrmAdminCrmProjectsIdRouteImport } from './routes/_crm/admin/crm/projects/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/_crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeInspectionRoute = FreeInspectionRouteImport.update({
  id: '/free-inspection',
  path: '/free-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolCleaningFriscoTxRoute = PoolCleaningFriscoTxRouteImport.update({
  id: '/pool-cleaning-frisco-tx',
  path: '/pool-cleaning-frisco-tx',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestInspectionRoute = RequestInspectionRouteImport.update({
  id: '/request-inspection',
  path: '/request-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCleaningRoute = AdminCleaningRouteImport.update({
  id: '/admin/cleaning',
  path: '/admin/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignsRoute = AdminDesignsRouteImport.update({
  id: '/admin/designs',
  path: '/admin/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/admin/store',
  path: '/admin/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSplatRoute = CrmSplatRouteImport.update({
  id: '/crm/$',
  path: '/crm/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmAppRoute = AdminCrmAppRouteImport.update({
  id: '/admin/crm/app',
  path: '/admin/crm/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmLegacyRoute = AdminCrmLegacyRouteImport.update({
  id: '/admin/crm/legacy',
  path: '/admin/crm/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmLoginRoute = AdminCrmLoginRouteImport.update({
  id: '/admin/crm/login',
  path: '/admin/crm/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmAdminCrmIndexRoute = CrmAdminCrmIndexRouteImport.update({
  id: '/admin/crm/',
  path: '/admin/crm/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmAlertsRoute = CrmAdminCrmAlertsRouteImport.update({
  id: '/admin/crm/alerts',
  path: '/admin/crm/alerts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmBreakEvenRoute = CrmAdminCrmBreakEvenRouteImport.update({
  id: '/admin/crm/break-even',
  path: '/admin/crm/break-even',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmConnectRoute = CrmAdminCrmConnectRouteImport.update({
  id: '/admin/crm/connect',
  path: '/admin/crm/connect',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmEmailRoute = CrmAdminCrmEmailRouteImport.update({
  id: '/admin/crm/email',
  path: '/admin/crm/email',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmFinanceRoute = CrmAdminCrmFinanceRouteImport.update({
  id: '/admin/crm/finance',
  path: '/admin/crm/finance',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmInventoryRoute = CrmAdminCrmInventoryRouteImport.update({
  id: '/admin/crm/inventory',
  path: '/admin/crm/inventory',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmJobsRoute = CrmAdminCrmJobsRouteImport.update({
  id: '/admin/crm/jobs',
  path: '/admin/crm/jobs',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmMarginRoute = CrmAdminCrmMarginRouteImport.update({
  id: '/admin/crm/margin',
  path: '/admin/crm/margin',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmPayPerPoolRoute = CrmAdminCrmPayPerPoolRouteImport.update({
  id: '/admin/crm/pay-per-pool',
  path: '/admin/crm/pay-per-pool',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmPipelineRoute = CrmAdminCrmPipelineRouteImport.update({
  id: '/admin/crm/pipeline',
  path: '/admin/crm/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmPricingMatrixRoute =
  CrmAdminCrmPricingMatrixRouteImport.update({
    id: '/admin/crm/pricing-matrix',
    path: '/admin/crm/pricing-matrix',
    getParentRoute: () => CrmRoute,
  } as any)
const CrmAdminCrmProductsRoute = CrmAdminCrmProductsRouteImport.update({
  id: '/admin/crm/products',
  path: '/admin/crm/products',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmQcReviewRoute = CrmAdminCrmQcReviewRouteImport.update({
  id: '/admin/crm/qc-review',
  path: '/admin/crm/qc-review',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmReportsRoute = CrmAdminCrmReportsRouteImport.update({
  id: '/admin/crm/reports',
  path: '/admin/crm/reports',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmRevenueGrowthRoute =
  CrmAdminCrmRevenueGrowthRouteImport.update({
    id: '/admin/crm/revenue-growth',
    path: '/admin/crm/revenue-growth',
    getParentRoute: () => CrmRoute,
  } as any)
const CrmAdminCrmReviewsRoute = CrmAdminCrmReviewsRouteImport.update({
  id: '/admin/crm/reviews',
  path: '/admin/crm/reviews',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmScorecardRoute = CrmAdminCrmScorecardRouteImport.update({
  id: '/admin/crm/scorecard',
  path: '/admin/crm/scorecard',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmSecurityRoute = CrmAdminCrmSecurityRouteImport.update({
  id: '/admin/crm/security',
  path: '/admin/crm/security',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmServicePlansRoute = CrmAdminCrmServicePlansRouteImport.update({
  id: '/admin/crm/service-plans',
  path: '/admin/crm/service-plans',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmSettingsRoute = CrmAdminCrmSettingsRouteImport.update({
  id: '/admin/crm/settings',
  path: '/admin/crm/settings',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmTechniciansRoute = CrmAdminCrmTechniciansRouteImport.update({
  id: '/admin/crm/technicians',
  path: '/admin/crm/technicians',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmTrucksRoute = CrmAdminCrmTrucksRouteImport.update({
  id: '/admin/crm/trucks',
  path: '/admin/crm/trucks',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmWaterLabRoute = CrmAdminCrmWaterLabRouteImport.update({
  id: '/admin/crm/water-lab',
  path: '/admin/crm/water-lab',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmCustomersIndexRoute =
  CrmAdminCrmCustomersIndexRouteImport.update({
    id: '/admin/crm/customers/',
    path: '/admin/crm/customers/',
    getParentRoute: () => CrmRoute,
  } as any)
const CrmAdminCrmCustomersIdRoute = CrmAdminCrmCustomersIdRouteImport.update({
  id: '/admin/crm/customers/$id',
  path: '/admin/crm/customers/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAdminCrmProjectsIndexRoute =
  CrmAdminCrmProjectsIndexRouteImport.update({
    id: '/admin/crm/projects/',
    path: '/admin/crm/projects/',
    getParentRoute: () => CrmRoute,
  } as any)
const CrmAdminCrmProjectsIdRoute = CrmAdminCrmProjectsIdRouteImport.update({
  id: '/admin/crm/projects/$id',
  path: '/admin/crm/projects/$id',
  getParentRoute: () => CrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/free-inspection': typeof FreeInspectionRoute
  '/pool-cleaning-frisco-tx': typeof PoolCleaningFriscoTxRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-inspection': typeof RequestInspectionRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/cleaning': typeof AdminCleaningRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/team': typeof AdminTeamRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/crm/$': typeof CrmSplatRoute
  '/review/$token': typeof ReviewTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/admin/crm/app': typeof AdminCrmAppRoute
  '/admin/crm/legacy': typeof AdminCrmLegacyRoute
  '/admin/crm/login': typeof AdminCrmLoginRoute
  '/admin/crm/alerts': typeof CrmAdminCrmAlertsRoute
  '/admin/crm/break-even': typeof CrmAdminCrmBreakEvenRoute
  '/admin/crm/connect': typeof CrmAdminCrmConnectRoute
  '/admin/crm/email': typeof CrmAdminCrmEmailRoute
  '/admin/crm/finance': typeof CrmAdminCrmFinanceRoute
  '/admin/crm/inventory': typeof CrmAdminCrmInventoryRoute
  '/admin/crm/jobs': typeof CrmAdminCrmJobsRoute
  '/admin/crm/margin': typeof CrmAdminCrmMarginRoute
  '/admin/crm/pay-per-pool': typeof CrmAdminCrmPayPerPoolRoute
  '/admin/crm/pipeline': typeof CrmAdminCrmPipelineRoute
  '/admin/crm/pricing-matrix': typeof CrmAdminCrmPricingMatrixRoute
  '/admin/crm/products': typeof CrmAdminCrmProductsRoute
  '/admin/crm/qc-review': typeof CrmAdminCrmQcReviewRoute
  '/admin/crm/reports': typeof CrmAdminCrmReportsRoute
  '/admin/crm/revenue-growth': typeof CrmAdminCrmRevenueGrowthRoute
  '/admin/crm/reviews': typeof CrmAdminCrmReviewsRoute
  '/admin/crm/scorecard': typeof CrmAdminCrmScorecardRoute
  '/admin/crm/security': typeof CrmAdminCrmSecurityRoute
  '/admin/crm/service-plans': typeof CrmAdminCrmServicePlansRoute
  '/admin/crm/settings': typeof CrmAdminCrmSettingsRoute
  '/admin/crm/technicians': typeof CrmAdminCrmTechniciansRoute
  '/admin/crm/trucks': typeof CrmAdminCrmTrucksRoute
  '/admin/crm/water-lab': typeof CrmAdminCrmWaterLabRoute
  '/admin/crm/': typeof CrmAdminCrmIndexRoute
  '/admin/crm/customers/$id': typeof CrmAdminCrmCustomersIdRoute
  '/admin/crm/projects/$id': typeof CrmAdminCrmProjectsIdRoute
  '/admin/crm/customers/': typeof CrmAdminCrmCustomersIndexRoute
  '/admin/crm/projects/': typeof CrmAdminCrmProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/free-inspection': typeof FreeInspectionRoute
  '/pool-cleaning-frisco-tx': typeof PoolCleaningFriscoTxRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-inspection': typeof RequestInspectionRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/cleaning': typeof AdminCleaningRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/team': typeof AdminTeamRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/crm/$': typeof CrmSplatRoute
  '/review/$token': typeof ReviewTokenRoute
  '/admin': typeof AdminIndexRoute
  '/crm': typeof CrmIndexRoute
  '/admin/crm/app': typeof AdminCrmAppRoute
  '/admin/crm/legacy': typeof AdminCrmLegacyRoute
  '/admin/crm/login': typeof AdminCrmLoginRoute
  '/admin/crm/alerts': typeof CrmAdminCrmAlertsRoute
  '/admin/crm/break-even': typeof CrmAdminCrmBreakEvenRoute
  '/admin/crm/connect': typeof CrmAdminCrmConnectRoute
  '/admin/crm/email': typeof CrmAdminCrmEmailRoute
  '/admin/crm/finance': typeof CrmAdminCrmFinanceRoute
  '/admin/crm/inventory': typeof CrmAdminCrmInventoryRoute
  '/admin/crm/jobs': typeof CrmAdminCrmJobsRoute
  '/admin/crm/margin': typeof CrmAdminCrmMarginRoute
  '/admin/crm/pay-per-pool': typeof CrmAdminCrmPayPerPoolRoute
  '/admin/crm/pipeline': typeof CrmAdminCrmPipelineRoute
  '/admin/crm/pricing-matrix': typeof CrmAdminCrmPricingMatrixRoute
  '/admin/crm/products': typeof CrmAdminCrmProductsRoute
  '/admin/crm/qc-review': typeof CrmAdminCrmQcReviewRoute
  '/admin/crm/reports': typeof CrmAdminCrmReportsRoute
  '/admin/crm/revenue-growth': typeof CrmAdminCrmRevenueGrowthRoute
  '/admin/crm/reviews': typeof CrmAdminCrmReviewsRoute
  '/admin/crm/scorecard': typeof CrmAdminCrmScorecardRoute
  '/admin/crm/security': typeof CrmAdminCrmSecurityRoute
  '/admin/crm/service-plans': typeof CrmAdminCrmServicePlansRoute
  '/admin/crm/settings': typeof CrmAdminCrmSettingsRoute
  '/admin/crm/technicians': typeof CrmAdminCrmTechniciansRoute
  '/admin/crm/trucks': typeof CrmAdminCrmTrucksRoute
  '/admin/crm/water-lab': typeof CrmAdminCrmWaterLabRoute
  '/admin/crm': typeof CrmAdminCrmIndexRoute
  '/admin/crm/customers/$id': typeof CrmAdminCrmCustomersIdRoute
  '/admin/crm/projects/$id': typeof CrmAdminCrmProjectsIdRoute
  '/admin/crm/customers': typeof CrmAdminCrmCustomersIndexRoute
  '/admin/crm/projects': typeof CrmAdminCrmProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_crm': typeof CrmRouteWithChildren
  '/auth': typeof AuthRoute
  '/free-inspection': typeof FreeInspectionRoute
  '/pool-cleaning-frisco-tx': typeof PoolCleaningFriscoTxRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-inspection': typeof RequestInspectionRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/cleaning': typeof AdminCleaningRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/team': typeof AdminTeamRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/crm/$': typeof CrmSplatRoute
  '/review/$token': typeof ReviewTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/admin/crm/app': typeof AdminCrmAppRoute
  '/admin/crm/legacy': typeof AdminCrmLegacyRoute
  '/admin/crm/login': typeof AdminCrmLoginRoute
  '/_crm/admin/crm/alerts': typeof CrmAdminCrmAlertsRoute
  '/_crm/admin/crm/break-even': typeof CrmAdminCrmBreakEvenRoute
  '/_crm/admin/crm/connect': typeof CrmAdminCrmConnectRoute
  '/_crm/admin/crm/email': typeof CrmAdminCrmEmailRoute
  '/_crm/admin/crm/finance': typeof CrmAdminCrmFinanceRoute
  '/_crm/admin/crm/inventory': typeof CrmAdminCrmInventoryRoute
  '/_crm/admin/crm/jobs': typeof CrmAdminCrmJobsRoute
  '/_crm/admin/crm/margin': typeof CrmAdminCrmMarginRoute
  '/_crm/admin/crm/pay-per-pool': typeof CrmAdminCrmPayPerPoolRoute
  '/_crm/admin/crm/pipeline': typeof CrmAdminCrmPipelineRoute
  '/_crm/admin/crm/pricing-matrix': typeof CrmAdminCrmPricingMatrixRoute
  '/_crm/admin/crm/products': typeof CrmAdminCrmProductsRoute
  '/_crm/admin/crm/qc-review': typeof CrmAdminCrmQcReviewRoute
  '/_crm/admin/crm/reports': typeof CrmAdminCrmReportsRoute
  '/_crm/admin/crm/revenue-growth': typeof CrmAdminCrmRevenueGrowthRoute
  '/_crm/admin/crm/reviews': typeof CrmAdminCrmReviewsRoute
  '/_crm/admin/crm/scorecard': typeof CrmAdminCrmScorecardRoute
  '/_crm/admin/crm/security': typeof CrmAdminCrmSecurityRoute
  '/_crm/admin/crm/service-plans': typeof CrmAdminCrmServicePlansRoute
  '/_crm/admin/crm/settings': typeof CrmAdminCrmSettingsRoute
  '/_crm/admin/crm/technicians': typeof CrmAdminCrmTechniciansRoute
  '/_crm/admin/crm/trucks': typeof CrmAdminCrmTrucksRoute
  '/_crm/admin/crm/water-lab': typeof CrmAdminCrmWaterLabRoute
  '/_crm/admin/crm/': typeof CrmAdminCrmIndexRoute
  '/_crm/admin/crm/customers/$id': typeof CrmAdminCrmCustomersIdRoute
  '/_crm/admin/crm/projects/$id': typeof CrmAdminCrmProjectsIdRoute
  '/_crm/admin/crm/customers/': typeof CrmAdminCrmCustomersIndexRoute
  '/_crm/admin/crm/projects/': typeof CrmAdminCrmProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/free-inspection'
    | '/pool-cleaning-frisco-tx'
    | '/portal'
    | '/privacy'
    | '/privacy-policy'
    | '/request-inspection'
    | '/services'
    | '/set-password'
    | '/terms'
    | '/terms-and-conditions'
    | '/admin/activity'
    | '/admin/cleaning'
    | '/admin/designs'
    | '/admin/store'
    | '/admin/team'
    | '/checkout/return'
    | '/crm/$'
    | '/review/$token'
    | '/admin/'
    | '/crm/'
    | '/admin/crm/app'
    | '/admin/crm/legacy'
    | '/admin/crm/login'
    | '/admin/crm/alerts'
    | '/admin/crm/break-even'
    | '/admin/crm/connect'
    | '/admin/crm/email'
    | '/admin/crm/finance'
    | '/admin/crm/inventory'
    | '/admin/crm/jobs'
    | '/admin/crm/margin'
    | '/admin/crm/pay-per-pool'
    | '/admin/crm/pipeline'
    | '/admin/crm/pricing-matrix'
    | '/admin/crm/products'
    | '/admin/crm/qc-review'
    | '/admin/crm/reports'
    | '/admin/crm/revenue-growth'
    | '/admin/crm/reviews'
    | '/admin/crm/scorecard'
    | '/admin/crm/security'
    | '/admin/crm/service-plans'
    | '/admin/crm/settings'
    | '/admin/crm/technicians'
    | '/admin/crm/trucks'
    | '/admin/crm/water-lab'
    | '/admin/crm/'
    | '/admin/crm/customers/$id'
    | '/admin/crm/projects/$id'
    | '/admin/crm/customers/'
    | '/admin/crm/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/free-inspection'
    | '/pool-cleaning-frisco-tx'
    | '/portal'
    | '/privacy'
    | '/privacy-policy'
    | '/request-inspection'
    | '/services'
    | '/set-password'
    | '/terms'
    | '/terms-and-conditions'
    | '/admin/activity'
    | '/admin/cleaning'
    | '/admin/designs'
    | '/admin/store'
    | '/admin/team'
    | '/checkout/return'
    | '/crm/$'
    | '/review/$token'
    | '/admin'
    | '/crm'
    | '/admin/crm/app'
    | '/admin/crm/legacy'
    | '/admin/crm/login'
    | '/admin/crm/alerts'
    | '/admin/crm/break-even'
    | '/admin/crm/connect'
    | '/admin/crm/email'
    | '/admin/crm/finance'
    | '/admin/crm/inventory'
    | '/admin/crm/jobs'
    | '/admin/crm/margin'
    | '/admin/crm/pay-per-pool'
    | '/admin/crm/pipeline'
    | '/admin/crm/pricing-matrix'
    | '/admin/crm/products'
    | '/admin/crm/qc-review'
    | '/admin/crm/reports'
    | '/admin/crm/revenue-growth'
    | '/admin/crm/reviews'
    | '/admin/crm/scorecard'
    | '/admin/crm/security'
    | '/admin/crm/service-plans'
    | '/admin/crm/settings'
    | '/admin/crm/technicians'
    | '/admin/crm/trucks'
    | '/admin/crm/water-lab'
    | '/admin/crm'
    | '/admin/crm/customers/$id'
    | '/admin/crm/projects/$id'
    | '/admin/crm/customers'
    | '/admin/crm/projects'
  id:
    | '__root__'
    | '/'
    | '/_crm'
    | '/auth'
    | '/free-inspection'
    | '/pool-cleaning-frisco-tx'
    | '/portal'
    | '/privacy'
    | '/privacy-policy'
    | '/request-inspection'
    | '/services'
    | '/set-password'
    | '/terms'
    | '/terms-and-conditions'
    | '/admin/activity'
    | '/admin/cleaning'
    | '/admin/designs'
    | '/admin/store'
    | '/admin/team'
    | '/checkout/return'
    | '/crm/$'
    | '/review/$token'
    | '/admin/'
    | '/crm/'
    | '/admin/crm/app'
    | '/admin/crm/legacy'
    | '/admin/crm/login'
    | '/_crm/admin/crm/alerts'
    | '/_crm/admin/crm/break-even'
    | '/_crm/admin/crm/connect'
    | '/_crm/admin/crm/email'
    | '/_crm/admin/crm/finance'
    | '/_crm/admin/crm/inventory'
    | '/_crm/admin/crm/jobs'
    | '/_crm/admin/crm/margin'
    | '/_crm/admin/crm/pay-per-pool'
    | '/_crm/admin/crm/pipeline'
    | '/_crm/admin/crm/pricing-matrix'
    | '/_crm/admin/crm/products'
    | '/_crm/admin/crm/qc-review'
    | '/_crm/admin/crm/reports'
    | '/_crm/admin/crm/revenue-growth'
    | '/_crm/admin/crm/reviews'
    | '/_crm/admin/crm/scorecard'
    | '/_crm/admin/crm/security'
    | '/_crm/admin/crm/service-plans'
    | '/_crm/admin/crm/settings'
    | '/_crm/admin/crm/technicians'
    | '/_crm/admin/crm/trucks'
    | '/_crm/admin/crm/water-lab'
    | '/_crm/admin/crm/'
    | '/_crm/admin/crm/customers/$id'
    | '/_crm/admin/crm/projects/$id'
    | '/_crm/admin/crm/customers/'
    | '/_crm/admin/crm/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  AuthRoute: typeof AuthRoute
  FreeInspectionRoute: typeof FreeInspectionRoute
  PoolCleaningFriscoTxRoute: typeof PoolCleaningFriscoTxRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RequestInspectionRoute: typeof RequestInspectionRoute
  ServicesRoute: typeof ServicesRoute
  SetPasswordRoute: typeof SetPasswordRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminCleaningRoute: typeof AdminCleaningRoute
  AdminDesignsRoute: typeof AdminDesignsRoute
  AdminStoreRoute: typeof AdminStoreRoute
  AdminTeamRoute: typeof AdminTeamRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CrmSplatRoute: typeof CrmSplatRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CrmIndexRoute: typeof CrmIndexRoute
  AdminCrmAppRoute: typeof AdminCrmAppRoute
  AdminCrmLegacyRoute: typeof AdminCrmLegacyRoute
  AdminCrmLoginRoute: typeof AdminCrmLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_crm': {
      id: '/_crm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-inspection': {
      id: '/free-inspection'
      path: '/free-inspection'
      fullPath: '/free-inspection'
      preLoaderRoute: typeof FreeInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-cleaning-frisco-tx': {
      id: '/pool-cleaning-frisco-tx'
      path: '/pool-cleaning-frisco-tx'
      fullPath: '/pool-cleaning-frisco-tx'
      preLoaderRoute: typeof PoolCleaningFriscoTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-inspection': {
      id: '/request-inspection'
      path: '/request-inspection'
      fullPath: '/request-inspection'
      preLoaderRoute: typeof RequestInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cleaning': {
      id: '/admin/cleaning'
      path: '/admin/cleaning'
      fullPath: '/admin/cleaning'
      preLoaderRoute: typeof AdminCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/designs': {
      id: '/admin/designs'
      path: '/admin/designs'
      fullPath: '/admin/designs'
      preLoaderRoute: typeof AdminDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/admin/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$': {
      id: '/crm/$'
      path: '/crm/$'
      fullPath: '/crm/$'
      preLoaderRoute: typeof CrmSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/app': {
      id: '/admin/crm/app'
      path: '/admin/crm/app'
      fullPath: '/admin/crm/app'
      preLoaderRoute: typeof AdminCrmAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/legacy': {
      id: '/admin/crm/legacy'
      path: '/admin/crm/legacy'
      fullPath: '/admin/crm/legacy'
      preLoaderRoute: typeof AdminCrmLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/login': {
      id: '/admin/crm/login'
      path: '/admin/crm/login'
      fullPath: '/admin/crm/login'
      preLoaderRoute: typeof AdminCrmLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_crm/admin/crm/': {
      id: '/_crm/admin/crm/'
      path: '/admin/crm'
      fullPath: '/admin/crm/'
      preLoaderRoute: typeof CrmAdminCrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/alerts': {
      id: '/_crm/admin/crm/alerts'
      path: '/admin/crm/alerts'
      fullPath: '/admin/crm/alerts'
      preLoaderRoute: typeof CrmAdminCrmAlertsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/break-even': {
      id: '/_crm/admin/crm/break-even'
      path: '/admin/crm/break-even'
      fullPath: '/admin/crm/break-even'
      preLoaderRoute: typeof CrmAdminCrmBreakEvenRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/connect': {
      id: '/_crm/admin/crm/connect'
      path: '/admin/crm/connect'
      fullPath: '/admin/crm/connect'
      preLoaderRoute: typeof CrmAdminCrmConnectRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/email': {
      id: '/_crm/admin/crm/email'
      path: '/admin/crm/email'
      fullPath: '/admin/crm/email'
      preLoaderRoute: typeof CrmAdminCrmEmailRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/finance': {
      id: '/_crm/admin/crm/finance'
      path: '/admin/crm/finance'
      fullPath: '/admin/crm/finance'
      preLoaderRoute: typeof CrmAdminCrmFinanceRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/inventory': {
      id: '/_crm/admin/crm/inventory'
      path: '/admin/crm/inventory'
      fullPath: '/admin/crm/inventory'
      preLoaderRoute: typeof CrmAdminCrmInventoryRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/jobs': {
      id: '/_crm/admin/crm/jobs'
      path: '/admin/crm/jobs'
      fullPath: '/admin/crm/jobs'
      preLoaderRoute: typeof CrmAdminCrmJobsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/margin': {
      id: '/_crm/admin/crm/margin'
      path: '/admin/crm/margin'
      fullPath: '/admin/crm/margin'
      preLoaderRoute: typeof CrmAdminCrmMarginRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/pay-per-pool': {
      id: '/_crm/admin/crm/pay-per-pool'
      path: '/admin/crm/pay-per-pool'
      fullPath: '/admin/crm/pay-per-pool'
      preLoaderRoute: typeof CrmAdminCrmPayPerPoolRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/pipeline': {
      id: '/_crm/admin/crm/pipeline'
      path: '/admin/crm/pipeline'
      fullPath: '/admin/crm/pipeline'
      preLoaderRoute: typeof CrmAdminCrmPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/pricing-matrix': {
      id: '/_crm/admin/crm/pricing-matrix'
      path: '/admin/crm/pricing-matrix'
      fullPath: '/admin/crm/pricing-matrix'
      preLoaderRoute: typeof CrmAdminCrmPricingMatrixRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/products': {
      id: '/_crm/admin/crm/products'
      path: '/admin/crm/products'
      fullPath: '/admin/crm/products'
      preLoaderRoute: typeof CrmAdminCrmProductsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/qc-review': {
      id: '/_crm/admin/crm/qc-review'
      path: '/admin/crm/qc-review'
      fullPath: '/admin/crm/qc-review'
      preLoaderRoute: typeof CrmAdminCrmQcReviewRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/reports': {
      id: '/_crm/admin/crm/reports'
      path: '/admin/crm/reports'
      fullPath: '/admin/crm/reports'
      preLoaderRoute: typeof CrmAdminCrmReportsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/revenue-growth': {
      id: '/_crm/admin/crm/revenue-growth'
      path: '/admin/crm/revenue-growth'
      fullPath: '/admin/crm/revenue-growth'
      preLoaderRoute: typeof CrmAdminCrmRevenueGrowthRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/reviews': {
      id: '/_crm/admin/crm/reviews'
      path: '/admin/crm/reviews'
      fullPath: '/admin/crm/reviews'
      preLoaderRoute: typeof CrmAdminCrmReviewsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/scorecard': {
      id: '/_crm/admin/crm/scorecard'
      path: '/admin/crm/scorecard'
      fullPath: '/admin/crm/scorecard'
      preLoaderRoute: typeof CrmAdminCrmScorecardRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/security': {
      id: '/_crm/admin/crm/security'
      path: '/admin/crm/security'
      fullPath: '/admin/crm/security'
      preLoaderRoute: typeof CrmAdminCrmSecurityRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/service-plans': {
      id: '/_crm/admin/crm/service-plans'
      path: '/admin/crm/service-plans'
      fullPath: '/admin/crm/service-plans'
      preLoaderRoute: typeof CrmAdminCrmServicePlansRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/settings': {
      id: '/_crm/admin/crm/settings'
      path: '/admin/crm/settings'
      fullPath: '/admin/crm/settings'
      preLoaderRoute: typeof CrmAdminCrmSettingsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/technicians': {
      id: '/_crm/admin/crm/technicians'
      path: '/admin/crm/technicians'
      fullPath: '/admin/crm/technicians'
      preLoaderRoute: typeof CrmAdminCrmTechniciansRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/trucks': {
      id: '/_crm/admin/crm/trucks'
      path: '/admin/crm/trucks'
      fullPath: '/admin/crm/trucks'
      preLoaderRoute: typeof CrmAdminCrmTrucksRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/water-lab': {
      id: '/_crm/admin/crm/water-lab'
      path: '/admin/crm/water-lab'
      fullPath: '/admin/crm/water-lab'
      preLoaderRoute: typeof CrmAdminCrmWaterLabRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/customers/': {
      id: '/_crm/admin/crm/customers/'
      path: '/admin/crm/customers'
      fullPath: '/admin/crm/customers/'
      preLoaderRoute: typeof CrmAdminCrmCustomersIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/customers/$id': {
      id: '/_crm/admin/crm/customers/$id'
      path: '/admin/crm/customers/$id'
      fullPath: '/admin/crm/customers/$id'
      preLoaderRoute: typeof CrmAdminCrmCustomersIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/projects/': {
      id: '/_crm/admin/crm/projects/'
      path: '/admin/crm/projects'
      fullPath: '/admin/crm/projects/'
      preLoaderRoute: typeof CrmAdminCrmProjectsIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_crm/admin/crm/projects/$id': {
      id: '/_crm/admin/crm/projects/$id'
      path: '/admin/crm/projects/$id'
      fullPath: '/admin/crm/projects/$id'
      preLoaderRoute: typeof CrmAdminCrmProjectsIdRouteImport
      parentRoute: typeof CrmRoute
    }
  }
}

interface CrmRouteChildren {
  CrmAdminCrmAlertsRoute: typeof CrmAdminCrmAlertsRoute
  CrmAdminCrmBreakEvenRoute: typeof CrmAdminCrmBreakEvenRoute
  CrmAdminCrmConnectRoute: typeof CrmAdminCrmConnectRoute
  CrmAdminCrmEmailRoute: typeof CrmAdminCrmEmailRoute
  CrmAdminCrmFinanceRoute: typeof CrmAdminCrmFinanceRoute
  CrmAdminCrmInventoryRoute: typeof CrmAdminCrmInventoryRoute
  CrmAdminCrmJobsRoute: typeof CrmAdminCrmJobsRoute
  CrmAdminCrmMarginRoute: typeof CrmAdminCrmMarginRoute
  CrmAdminCrmPayPerPoolRoute: typeof CrmAdminCrmPayPerPoolRoute
  CrmAdminCrmPipelineRoute: typeof CrmAdminCrmPipelineRoute
  CrmAdminCrmPricingMatrixRoute: typeof CrmAdminCrmPricingMatrixRoute
  CrmAdminCrmProductsRoute: typeof CrmAdminCrmProductsRoute
  CrmAdminCrmQcReviewRoute: typeof CrmAdminCrmQcReviewRoute
  CrmAdminCrmReportsRoute: typeof CrmAdminCrmReportsRoute
  CrmAdminCrmRevenueGrowthRoute: typeof CrmAdminCrmRevenueGrowthRoute
  CrmAdminCrmReviewsRoute: typeof CrmAdminCrmReviewsRoute
  CrmAdminCrmScorecardRoute: typeof CrmAdminCrmScorecardRoute
  CrmAdminCrmSecurityRoute: typeof CrmAdminCrmSecurityRoute
  CrmAdminCrmServicePlansRoute: typeof CrmAdminCrmServicePlansRoute
  CrmAdminCrmSettingsRoute: typeof CrmAdminCrmSettingsRoute
  CrmAdminCrmTechniciansRoute: typeof CrmAdminCrmTechniciansRoute
  CrmAdminCrmTrucksRoute: typeof CrmAdminCrmTrucksRoute
  CrmAdminCrmWaterLabRoute: typeof CrmAdminCrmWaterLabRoute
  CrmAdminCrmIndexRoute: typeof CrmAdminCrmIndexRoute
  CrmAdminCrmCustomersIdRoute: typeof CrmAdminCrmCustomersIdRoute
  CrmAdminCrmProjectsIdRoute: typeof CrmAdminCrmProjectsIdRoute
  CrmAdminCrmCustomersIndexRoute: typeof CrmAdminCrmCustomersIndexRoute
  CrmAdminCrmProjectsIndexRoute: typeof CrmAdminCrmProjectsIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAdminCrmAlertsRoute: CrmAdminCrmAlertsRoute,
  CrmAdminCrmBreakEvenRoute: CrmAdminCrmBreakEvenRoute,
  CrmAdminCrmConnectRoute: CrmAdminCrmConnectRoute,
  CrmAdminCrmEmailRoute: CrmAdminCrmEmailRoute,
  CrmAdminCrmFinanceRoute: CrmAdminCrmFinanceRoute,
  CrmAdminCrmInventoryRoute: CrmAdminCrmInventoryRoute,
  CrmAdminCrmJobsRoute: CrmAdminCrmJobsRoute,
  CrmAdminCrmMarginRoute: CrmAdminCrmMarginRoute,
  CrmAdminCrmPayPerPoolRoute: CrmAdminCrmPayPerPoolRoute,
  CrmAdminCrmPipelineRoute: CrmAdminCrmPipelineRoute,
  CrmAdminCrmPricingMatrixRoute: CrmAdminCrmPricingMatrixRoute,
  CrmAdminCrmProductsRoute: CrmAdminCrmProductsRoute,
  CrmAdminCrmQcReviewRoute: CrmAdminCrmQcReviewRoute,
  CrmAdminCrmReportsRoute: CrmAdminCrmReportsRoute,
  CrmAdminCrmRevenueGrowthRoute: CrmAdminCrmRevenueGrowthRoute,
  CrmAdminCrmReviewsRoute: CrmAdminCrmReviewsRoute,
  CrmAdminCrmScorecardRoute: CrmAdminCrmScorecardRoute,
  CrmAdminCrmSecurityRoute: CrmAdminCrmSecurityRoute,
  CrmAdminCrmServicePlansRoute: CrmAdminCrmServicePlansRoute,
  CrmAdminCrmSettingsRoute: CrmAdminCrmSettingsRoute,
  CrmAdminCrmTechniciansRoute: CrmAdminCrmTechniciansRoute,
  CrmAdminCrmTrucksRoute: CrmAdminCrmTrucksRoute,
  CrmAdminCrmWaterLabRoute: CrmAdminCrmWaterLabRoute,
  CrmAdminCrmIndexRoute: CrmAdminCrmIndexRoute,
  CrmAdminCrmCustomersIdRoute: CrmAdminCrmCustomersIdRoute,
  CrmAdminCrmProjectsIdRoute: CrmAdminCrmProjectsIdRoute,
  CrmAdminCrmCustomersIndexRoute: CrmAdminCrmCustomersIndexRoute,
  CrmAdminCrmProjectsIndexRoute: CrmAdminCrmProjectsIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  AuthRoute: AuthRoute,
  FreeInspectionRoute: FreeInspectionRoute,
  PoolCleaningFriscoTxRoute: PoolCleaningFriscoTxRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RequestInspectionRoute: RequestInspectionRoute,
  ServicesRoute: ServicesRoute,
  SetPasswordRoute: SetPasswordRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminCleaningRoute: AdminCleaningRoute,
  AdminDesignsRoute: AdminDesignsRoute,
  AdminStoreRoute: AdminStoreRoute,
  AdminTeamRoute: AdminTeamRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CrmSplatRoute: CrmSplatRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  CrmIndexRoute: CrmIndexRoute,
  AdminCrmAppRoute: AdminCrmAppRoute,
  AdminCrmLegacyRoute: AdminCrmLegacyRoute,
  AdminCrmLoginRoute: AdminCrmLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
