CREATE SEQUENCE IF NOT EXISTS public.ss_pool_number_seq START 1000;
GRANT USAGE, SELECT ON SEQUENCE public.ss_pool_number_seq TO authenticated, service_role;
GRANT ALL ON TABLE public.ss_email_threads TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_internal_notes TO authenticated;
GRANT ALL ON TABLE public.ss_internal_notes TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_internal_tasks TO authenticated;
GRANT ALL ON TABLE public.ss_internal_tasks TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_invoice_reconciliation TO authenticated;
GRANT ALL ON TABLE public.ss_invoice_reconciliation TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_lead_appointments TO authenticated;
GRANT ALL ON TABLE public.ss_lead_appointments TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_native_push_tokens TO authenticated;
GRANT ALL ON TABLE public.ss_native_push_tokens TO service_role;
GRANT SELECT,INSERT,UPDATE ON TABLE public.ss_notification_prefs TO authenticated;
GRANT ALL ON TABLE public.ss_notification_prefs TO service_role;
GRANT SELECT,UPDATE ON TABLE public.ss_notifications TO authenticated;
GRANT ALL ON TABLE public.ss_notifications TO service_role;
GRANT SELECT,INSERT ON TABLE public.ss_payment_events TO authenticated;
GRANT ALL ON TABLE public.ss_payment_events TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_payment_pickups TO authenticated;
GRANT ALL ON TABLE public.ss_payment_pickups TO service_role;
GRANT SELECT,INSERT ON TABLE public.ss_payment_proofs TO authenticated;
GRANT ALL ON TABLE public.ss_payment_proofs TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_phone_optouts TO authenticated;
GRANT ALL ON TABLE public.ss_phone_optouts TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_pool_costs TO authenticated;
GRANT ALL ON TABLE public.ss_pool_costs TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_pricing_settings TO authenticated;
GRANT ALL ON TABLE public.ss_pricing_settings TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_push_subscriptions TO authenticated;
GRANT ALL ON TABLE public.ss_push_subscriptions TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_qr_batches TO authenticated;
GRANT ALL ON TABLE public.ss_qr_batches TO service_role;
GRANT SELECT ON TABLE public.ss_qr_scans TO authenticated;
GRANT ALL ON TABLE public.ss_qr_scans TO service_role;
GRANT SELECT ON TABLE public.ss_qr_tags TO authenticated;
GRANT ALL ON TABLE public.ss_qr_tags TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_quote_templates TO authenticated;
GRANT SELECT ON TABLE public.ss_quote_templates TO anon;
GRANT ALL ON TABLE public.ss_quote_templates TO service_role;
GRANT SELECT,INSERT ON TABLE public.ss_report_events TO authenticated;
GRANT ALL ON TABLE public.ss_report_events TO service_role;
GRANT SELECT ON TABLE public.ss_sla_alerts TO authenticated;
GRANT ALL ON TABLE public.ss_sla_alerts TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_sla_rules TO authenticated;
GRANT ALL ON TABLE public.ss_sla_rules TO service_role;
GRANT SELECT,INSERT,UPDATE ON TABLE public.ss_sla_templates TO authenticated;
GRANT ALL ON TABLE public.ss_sla_templates TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_staff_availability TO authenticated;
GRANT ALL ON TABLE public.ss_staff_availability TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_staff_time_off TO authenticated;
GRANT ALL ON TABLE public.ss_staff_time_off TO service_role;
GRANT SELECT,INSERT ON TABLE public.ss_task_audit TO authenticated;
GRANT ALL ON TABLE public.ss_task_audit TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_truck_stock TO authenticated;
GRANT ALL ON TABLE public.ss_truck_stock TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_vault_logins TO authenticated;
GRANT ALL ON TABLE public.ss_vault_logins TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ss_vendors TO authenticated;
GRANT ALL ON TABLE public.ss_vendors TO service_role;
GRANT SELECT,INSERT,UPDATE ON TABLE public.ss_visit_requests TO authenticated;
GRANT ALL ON TABLE public.ss_visit_requests TO service_role;
GRANT SELECT ON TABLE public.ss_webhook_secret_usage TO authenticated;
GRANT ALL ON TABLE public.ss_webhook_secret_usage TO service_role;
ALTER TABLE public.inspection_requests ADD COLUMN IF NOT EXISTS assigned_staff_id uuid;
ALTER TABLE public.inspection_requests ADD COLUMN IF NOT EXISTS customer_note text;
ALTER TABLE public.inspection_requests ADD COLUMN IF NOT EXISTS eta_at timestamp with time zone;
ALTER TABLE public.inspection_requests ADD COLUMN IF NOT EXISTS eta_window text;
ALTER TABLE public.inspection_requests ADD COLUMN IF NOT EXISTS status_changed_at timestamp with time zone;
ALTER TABLE public.ss_city_rates ADD COLUMN IF NOT EXISTS rate_basis text DEFAULT 'monthly'::text;
ALTER TABLE public.ss_contract_templates ADD COLUMN IF NOT EXISTS key text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS attribution jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS attribution_campaign text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS attribution_landing_page text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS became_customer_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS billing_anchor_date date;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS card_brand text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS card_last4 text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_baseline_psi numeric;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_clean_billing text DEFAULT 'monthly'::text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_clean_charge_type text DEFAULT 'none'::text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_clean_included boolean DEFAULT false;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_clean_price numeric(10,2) DEFAULT 35.00;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_identified_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_label_note text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_label_photo_url text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_psi_threshold numeric DEFAULT 19;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS filter_type text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS first_month_charge_amount numeric;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS first_month_charge_status text DEFAULT 'none'::text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS first_month_charged_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS first_touch_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS first_touch_placement text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS gate_code_updated_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS gate_code_updated_by uuid;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS gate_code_updated_by_name text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS gate_code_updated_by_role text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS house_photo_path text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS last_backwash_at date;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS last_cartridge_clean_at date;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS last_salt_cell_clean_at date;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS last_touch_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS last_touch_placement text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS needs_review boolean DEFAULT false;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS plan_id text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS pool_number text DEFAULT public.ss_next_pool_number();
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS pool_photo_path text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS pool_size_band text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS price_confirmed_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS price_confirmed_by text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS qr_tag_id text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS reviewed_by uuid;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS salt_cell_billing text DEFAULT 'monthly'::text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS salt_cell_charge_type text DEFAULT 'none'::text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS salt_cell_included boolean DEFAULT false;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS salt_cell_interval_days integer DEFAULT 120;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS salt_cell_price numeric(10,2) DEFAULT 15.00;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS salt_cell_quantity integer DEFAULT 1;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS sanitizer text DEFAULT 'chlorine'::text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS service_hold_at timestamp with time zone;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS service_hold_reason text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS signup_source text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS stripe_customer_id text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS stripe_payment_method_id text;
ALTER TABLE public.ss_customers ADD COLUMN IF NOT EXISTS waterfall_override jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.ss_inventory ADD COLUMN IF NOT EXISTS reorder_qty numeric;
ALTER TABLE public.ss_inventory ADD COLUMN IF NOT EXISTS vendor_id uuid;
ALTER TABLE public.ss_inventory_moves ADD COLUMN IF NOT EXISTS truck_id uuid;
ALTER TABLE public.ss_invoice_items ADD COLUMN IF NOT EXISTS internal_only boolean DEFAULT false;
ALTER TABLE public.ss_invoices ADD COLUMN IF NOT EXISTS currency text DEFAULT 'usd'::text;
ALTER TABLE public.ss_invoices ADD COLUMN IF NOT EXISTS hold_at timestamp with time zone;
ALTER TABLE public.ss_invoices ADD COLUMN IF NOT EXISTS past_due_at timestamp with time zone;
ALTER TABLE public.ss_invoices ADD COLUMN IF NOT EXISTS period_month date;
ALTER TABLE public.ss_invoices ADD COLUMN IF NOT EXISTS reminder_sent_at timestamp with time zone;
ALTER TABLE public.ss_jobs ADD COLUMN IF NOT EXISTS ended_at timestamp with time zone;
ALTER TABLE public.ss_jobs ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS assigned_at timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS assigned_staff_id uuid;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS campaign_id text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS channel text DEFAULT 'website'::text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS cta text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS first_response_at timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS intake_channel text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS intake_ref uuid;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS landing_page text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS last_reminder_at timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS next_action text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS next_action_due timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS next_action_owner_id uuid;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS next_action_set_at timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS opt_in_at timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS placement text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS referrer text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS reminder_count integer DEFAULT 0;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS session_id text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS sla_due_at timestamp with time zone;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS sla_status text DEFAULT 'on_track'::text;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS sms_opt_in boolean DEFAULT false;
ALTER TABLE public.ss_leads ADD COLUMN IF NOT EXISTS utm jsonb;
ALTER TABLE public.ss_payments ADD COLUMN IF NOT EXISTS confirmed_at timestamp with time zone;
ALTER TABLE public.ss_payments ADD COLUMN IF NOT EXISTS confirmed_by uuid;
ALTER TABLE public.ss_price_book ADD COLUMN IF NOT EXISTS addon_key text;
ALTER TABLE public.ss_price_book ADD COLUMN IF NOT EXISTS default_cost numeric(10,2) DEFAULT 0;
ALTER TABLE public.ss_price_book ADD COLUMN IF NOT EXISTS kind text DEFAULT 'one_time'::text;
ALTER TABLE public.ss_price_book ADD COLUMN IF NOT EXISTS price_max numeric;
ALTER TABLE public.ss_price_book ADD COLUMN IF NOT EXISTS target_margin_pct numeric(5,2);
ALTER TABLE public.ss_quote_items ADD COLUMN IF NOT EXISTS bundle_id uuid;
ALTER TABLE public.ss_quote_items ADD COLUMN IF NOT EXISTS bundle_includes jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.ss_quote_items ADD COLUMN IF NOT EXISTS bundle_name text;
ALTER TABLE public.ss_quote_items ADD COLUMN IF NOT EXISTS choice_group text;
ALTER TABLE public.ss_quote_items ADD COLUMN IF NOT EXISTS choice_required boolean DEFAULT false;
ALTER TABLE public.ss_quote_items ADD COLUMN IF NOT EXISTS itemized_unit_price numeric;
ALTER TABLE public.ss_route_schedules ADD COLUMN IF NOT EXISTS window_end time without time zone;
ALTER TABLE public.ss_route_schedules ADD COLUMN IF NOT EXISTS window_start time without time zone;
ALTER TABLE public.ss_staff ADD COLUMN IF NOT EXISTS finance_access boolean DEFAULT false;
ALTER TABLE public.ss_staff ADD COLUMN IF NOT EXISTS hourly_rate numeric;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS amount_paid numeric(10,2) DEFAULT 0;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS backwash_done boolean DEFAULT false;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS cartridge_cleaned boolean DEFAULT false;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS checkin_lat numeric;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS checkin_lng numeric;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS checkin_source text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS cost_items jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS cost_total numeric DEFAULT 0;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS customer_notified_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS filter_label_photo_url text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS filter_psi_after numeric;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS filter_psi_before numeric;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS filter_type text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS hold_manual boolean DEFAULT false;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS invoice_id uuid;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS labor_cost numeric DEFAULT 0;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS labor_hours numeric;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS late_fee numeric(10,2) DEFAULT 0;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS late_fee_applied_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS paid_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS parts_cost numeric DEFAULT 0;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS payment_method text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'unpaid'::text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS report_sent_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS report_url text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS safety_checks jsonb;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS safety_hazards text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS safety_ok boolean;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS safety_photos jsonb;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS safety_sent_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS service_amount numeric(10,2) DEFAULT 0;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS service_day text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS signature_name text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS signature_url text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS signed_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS signed_by text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS summary_emailed_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS swim_hold_reason text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS swim_ready_notified_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS swim_safe_at timestamp with time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS visit_kind text DEFAULT 'service'::text;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS window_end time without time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS window_start time without time zone;
ALTER TABLE public.ss_visits ADD COLUMN IF NOT EXISTS work_performed text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS access_notes text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS automation_brand text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS avg_depth_ft numeric;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS cleaner_brand text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS cleaner_type text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS features text[] DEFAULT '{}'::text[];
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS filter_baseline_psi numeric;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS filter_identified_at timestamp with time zone;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS filter_label_photo_url text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS filter_psi_threshold numeric DEFAULT 19;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS filter_type text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS gate_code text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS gate_location text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS has_dog boolean;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS heater_brand text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS heater_model text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS heater_type text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS last_backwash_at date;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS last_cartridge_clean_at date;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS length_ft numeric;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS profile_captured_at timestamp with time zone;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS profile_captured_by uuid;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS profile_photos jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS pump_brand text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS pump_hp text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS pump_model text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS pump_variable_speed boolean;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS salt_cell_brand text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS salt_cell_model text;
ALTER TABLE public.ss_water_bodies ADD COLUMN IF NOT EXISTS width_ft numeric;