
INSERT INTO public.pool_designs (title, description, style, features, image_path, category, media_type, stage_order, display_order) VALUES
('Classic Rectangle Plan', 'Top-down architectural blueprint for a 16x32 classic rectangular pool with dimensions, equipment legend, and scale bar.', 'Plan - Rectangle', ARRAY['16x32 ft','Skimmer + returns','3.5-5.5 ft depth','Step entry'], 'plans/01_rectangle.jpg', 'plan', 'image', NULL, 100),
('Roman End Plan', 'Roman end pool blueprint with semi-circular ends, sections, and full equipment legend.', 'Plan - Roman End', ARRAY['36x16 ft','Semi-circular ends','Plaster finish','18,720 gal'], 'plans/02_roman.jpg', 'plan', 'image', NULL, 101),
('Grecian Plan', 'Grecian pool blueprint with cut corners, plumbing legend, and equipment pad layout.', 'Plan - Grecian', ARRAY['28x44 ft','Cut corners','Step return','Air blower'], 'plans/03_grecian.jpg', 'plan', 'image', NULL, 102),
('Kidney Plan', 'Kidney-shaped pool blueprint with depth contours and equipment pad detail.', 'Plan - Kidney', ARRAY['32x22 ft','Organic curves','~16,500 gal','Heater + filter'], 'plans/04_kidney.jpg', 'plan', 'image', NULL, 103),
('Freeform Lagoon Plan', 'Freeform lagoon blueprint with beach entry, boulder waterfall, and depth contour schedule.', 'Plan - Freeform Lagoon', ARRAY['36x32 ft','Beach entry','Boulder waterfall','1,920 sq ft'], 'plans/05_lagoon.jpg', 'plan', 'image', NULL, 104),
('L-Shape with Spa Plan', 'L-shaped pool blueprint with attached spa, jet locations, and dimension call-outs.', 'Plan - L-Shape + Spa', ARRAY['24x28 ft L','Attached spa','Directional jets','Tile line'], 'plans/06_lshape.jpg', 'plan', 'image', NULL, 105),
('Lap Pool Plan', 'Long narrow lap pool blueprint with lane markers and entry steps.', 'Plan - Lap', ARRAY['10x50 ft','Lane markers','15,000 gal','Handrail steps'], 'plans/07_lap.jpg', 'plan', 'image', NULL, 106),
('Plunge / Cocktail Plan', 'Compact plunge pool blueprint with hydrotherapy jets and bench seating.', 'Plan - Plunge', ARRAY['10x8 ft','4 hydro jets','Bench seating','Pebble plaster'], 'plans/08_plunge.jpg', 'plan', 'image', NULL, 107),
('Modern Geometric + Spa Plan', 'Modern geometric pool blueprint with raised spa, tanning ledge, and deck jets.', 'Plan - Modern Geometric', ARRAY['26x14 ft','Raised spa','Tanning ledge','Deck jets + bubblers'], 'plans/09_modern.jpg', 'plan', 'image', NULL, 108),
('Infinity Edge Plan', 'Infinity edge pool blueprint with catch basin detail and section call-outs.', 'Plan - Infinity Edge', ARRAY['30x14 ft','Vanishing edge','Catch basin','Hillside lot'], 'plans/10_infinity.jpg', 'plan', 'image', NULL, 109);

INSERT INTO public.pool_designs (title, description, style, features, image_path, category, media_type, stage_order, display_order) VALUES
('Stage 1 - Layout & Site Prep', '3D animation: surveyors marking out the pool footprint with stakes, string lines, and spray paint.', 'Construction Stage', ARRAY['Survey','Layout','Permits','Utility marking'], 'construction/01_layout.mp4', 'construction', 'video', 1, 200),
('Stage 2 - Excavation', '3D animation: yellow excavator digging the pool hole, dirt piles, and dump trucks hauling off spoils.', 'Construction Stage', ARRAY['Excavator','Spoils removal','Grade check'], 'construction/02_excavation.mp4', 'construction', 'video', 2, 201),
('Stage 3 - Steel Rebar', '3D animation: workers tying the rebar grid forming the structural cage of the pool shell.', 'Construction Stage', ARRAY['#3 rebar','12 in grid','Bond beam','Inspection'], 'construction/03_rebar.mp4', 'construction', 'video', 3, 202),
('Stage 4 - Plumbing Rough-In', '3D animation: PVC plumbing installed for skimmers, returns, and main drain prior to gunite.', 'Construction Stage', ARRAY['Schedule 40 PVC','Skimmer lines','Main drain','Pressure test'], 'construction/04_plumbing.mp4', 'construction', 'video', 4, 203),
('Stage 5 - Gunite / Shotcrete', '3D animation: high-pressure spraying of structural concrete forming the pool shell.', 'Construction Stage', ARRAY['Shotcrete','Structural shell','28-day cure','Hand-troweled'], 'construction/05_gunite.mp4', 'construction', 'video', 5, 204),
('Stage 6 - Tile & Coping', '3D animation: installation of waterline mosaic tile and natural stone coping along the pool edge.', 'Construction Stage', ARRAY['Mosaic waterline','Travertine coping','6 in band'], 'construction/06_tile.mp4', 'construction', 'video', 6, 205),
('Stage 7 - Deck Pour', '3D animation: workers screeding and finishing the concrete patio deck around the pool.', 'Construction Stage', ARRAY['Broom finish','Expansion joints','Form work'], 'construction/07_deck.mp4', 'construction', 'video', 7, 206),
('Stage 8 - Plaster Interior', '3D animation: troweling smooth pebble plaster onto the pool walls and floor.', 'Construction Stage', ARRAY['Pebble Sheen','Hand-troweled','Acid start-up'], 'construction/08_plaster.mp4', 'construction', 'video', 8, 207),
('Stage 9 - Water Fill', '3D animation: time-lapse of clean water filling the brand new pool to the waterline.', 'Construction Stage', ARRAY['Continuous fill','No interruption','Chemistry start'], 'construction/09_fill.mp4', 'construction', 'video', 9, 208),
('Stage 10 - Finished Reveal', '3D animation: completed pool at dusk with lights on, landscaping, and patio furniture in place.', 'Construction Stage', ARRAY['LED lighting','Landscaping','Equipment startup','Owner handoff'], 'construction/10_finished.mp4', 'construction', 'video', 10, 209);
