DO $mig$
DECLARE s text;
BEGIN
  FOREACH s IN ARRAY ARRAY[
$q$ALTER TABLE ONLY public.ss_staff_time_off ADD CONSTRAINT ss_staff_time_off_tech_id_fkey FOREIGN KEY (tech_id) REFERENCES public.ss_staff(id) ON DELETE CASCADE$q$,
$q$ALTER TABLE ONLY public.ss_truck_stock ADD CONSTRAINT ss_truck_stock_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.ss_inventory(id) ON DELETE CASCADE$q$,
$q$ALTER TABLE ONLY public.ss_truck_stock ADD CONSTRAINT ss_truck_stock_truck_id_fkey FOREIGN KEY (truck_id) REFERENCES public.ss_trucks(id) ON DELETE CASCADE$q$,
$q$ALTER TABLE ONLY public.ss_vault_logins ADD CONSTRAINT ss_vault_logins_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.ss_vendors(id) ON DELETE SET NULL$q$,
$q$ALTER TABLE ONLY public.ss_visit_requests ADD CONSTRAINT ss_visit_requests_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.ss_customers(id) ON DELETE CASCADE$q$,
$q$ALTER TABLE ONLY public.ss_visit_requests ADD CONSTRAINT ss_visit_requests_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.ss_visits(id) ON DELETE SET NULL$q$,
$q$CREATE POLICY "Anyone can read active quote templates" ON public.ss_quote_templates FOR SELECT TO anon, authenticated USING ((is_active = true))$q$,
$q$CREATE POLICY "Crew can view qr batches" ON public.ss_qr_batches FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Crew can view qr tags" ON public.ss_qr_tags FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Crew sees their own qr scans" ON public.ss_qr_scans FOR SELECT TO authenticated USING ((staff_id = public.ss_my_staff_id()))$q$,
$q$CREATE POLICY "Customers can view their own qr tags" ON public.ss_qr_tags FOR SELECT TO authenticated USING ((customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)))$q$,
$q$CREATE POLICY "Customers create own visit requests" ON public.ss_visit_requests FOR INSERT TO authenticated WITH CHECK (((status = 'pending'::text) AND (quoted_price IS NULL) AND (visit_id IS NULL) AND (office_note IS NULL) AND ((customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)) OR public.ss_is_office())))$q$,
$q$CREATE POLICY "Customers read own visit requests" ON public.ss_visit_requests FOR SELECT TO authenticated USING (((customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)) OR public.ss_is_staff()))$q$,
$q$CREATE POLICY "Customers view own payment events" ON public.ss_payment_events FOR SELECT TO authenticated USING ((customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)))$q$,
$q$CREATE POLICY "Office can create access codes" ON public.ss_access_codes FOR INSERT TO authenticated WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office can read access codes" ON public.ss_access_codes FOR SELECT TO authenticated USING (public.ss_is_office())$q$,
$q$CREATE POLICY "Office can update access codes" ON public.ss_access_codes FOR UPDATE TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office decides visit requests" ON public.ss_visit_requests FOR UPDATE TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manage sla rules" ON public.ss_sla_rules TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manage sla templates" ON public.ss_sla_templates TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manages calls" ON public.ss_calls TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manages payment pickups" ON public.ss_payment_pickups TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manages phone optouts" ON public.ss_phone_optouts TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manages qr batches" ON public.ss_qr_batches TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manages qr tags" ON public.ss_qr_tags TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office manages truck stock" ON public.ss_truck_stock TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office read sla alerts" ON public.ss_sla_alerts FOR SELECT TO authenticated USING (public.ss_is_office())$q$,
$q$CREATE POLICY "Office reviews access requests" ON public.ss_access_requests FOR UPDATE TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office reviews qr scans" ON public.ss_qr_scans FOR SELECT TO authenticated USING (public.ss_is_office())$q$,
$q$CREATE POLICY "Office staff manage pool costs" ON public.ss_pool_costs TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office staff manage quote templates" ON public.ss_quote_templates TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "Office writes lead appointments" ON public.ss_lead_appointments TO authenticated USING (public.ss_is_staff()) WITH CHECK (public.ss_is_staff())$q$,
$q$CREATE POLICY "Owner can delete access codes" ON public.ss_access_codes FOR DELETE TO authenticated USING (public.ss_is_owner())$q$,
$q$CREATE POLICY "Owners manage vault logins" ON public.ss_vault_logins TO authenticated USING (public.ss_is_owner()) WITH CHECK (public.ss_is_owner())$q$,
$q$CREATE POLICY "Service role can manage native push tokens" ON public.ss_native_push_tokens TO service_role USING (true) WITH CHECK (true)$q$,
$q$CREATE POLICY "Signed-in users log their own report events" ON public.ss_report_events FOR INSERT TO authenticated WITH CHECK ((actor_user_id = auth.uid()))$q$,
$q$CREATE POLICY "Staff can manage reconciliation" ON public.ss_invoice_reconciliation TO authenticated USING (public.ss_is_staff()) WITH CHECK (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff can view backup sync state" ON public.ss_backup_sync FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff can view reconciliation" ON public.ss_invoice_reconciliation FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff manage payment events" ON public.ss_payment_events TO authenticated USING (public.ss_is_staff()) WITH CHECK (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff read lead appointments" ON public.ss_lead_appointments FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff read report events" ON public.ss_report_events FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff read sla rules" ON public.ss_sla_rules FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff read sla templates" ON public.ss_sla_templates FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Staff read truck stock" ON public.ss_truck_stock FOR SELECT TO authenticated USING (public.ss_is_staff())$q$,
$q$CREATE POLICY "Tech reads own customer calls" ON public.ss_calls FOR SELECT TO authenticated USING ((customer_id IN ( SELECT ss_customers.id FROM public.ss_customers WHERE (ss_customers.assigned_tech_id = public.ss_my_staff_id()))))$q$,
$q$CREATE POLICY "Techs read pickups for assigned visits" ON public.ss_payment_pickups FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM public.ss_visits v WHERE ((v.id = ss_payment_pickups.visit_id) AND (v.tech_id = public.ss_my_staff_id())))))$q$,
$q$CREATE POLICY "Techs update pickups for assigned visits" ON public.ss_payment_pickups FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1 FROM public.ss_visits v WHERE ((v.id = ss_payment_pickups.visit_id) AND (v.tech_id = public.ss_my_staff_id()))))) WITH CHECK ((EXISTS ( SELECT 1 FROM public.ss_visits v WHERE ((v.id = ss_payment_pickups.visit_id) AND (v.tech_id = public.ss_my_staff_id())))))$q$,
$q$CREATE POLICY "Users can manage own native push tokens" ON public.ss_native_push_tokens TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()))$q$,
$q$CREATE POLICY "Users create own access request" ON public.ss_access_requests FOR INSERT TO authenticated WITH CHECK (((user_id = auth.uid()) AND public.ss_can_claim_customer(customer_id)))$q$,
$q$CREATE POLICY "Users create own notification prefs" ON public.ss_notification_prefs FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()))$q$,
$q$CREATE POLICY "Users mark own notifications read" ON public.ss_notifications FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()))$q$,
$q$CREATE POLICY "Users read own access request" ON public.ss_access_requests FOR SELECT TO authenticated USING (((user_id = auth.uid()) OR public.ss_is_office()))$q$,
$q$CREATE POLICY "Users read own notification prefs" ON public.ss_notification_prefs FOR SELECT TO authenticated USING ((user_id = auth.uid()))$q$,
$q$CREATE POLICY "Users read own notifications" ON public.ss_notifications FOR SELECT TO authenticated USING ((user_id = auth.uid()))$q$,
$q$CREATE POLICY "Users update own notification prefs" ON public.ss_notification_prefs FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()))$q$,
$q$CREATE POLICY "customer opens own channel" ON public.ss_chat_channels FOR INSERT TO authenticated WITH CHECK (((kind = 'customer'::text) AND (customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids))))$q$,
$q$CREATE POLICY "customer reads own messages" ON public.ss_chat_messages FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM public.ss_chat_channels c WHERE ((c.id = ss_chat_messages.channel_id) AND (c.kind = 'customer'::text) AND (c.customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids))))))$q$,
$q$CREATE POLICY "customer sees own channel" ON public.ss_chat_channels FOR SELECT TO authenticated USING (((kind = 'customer'::text) AND (customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids))))$q$,
$q$CREATE POLICY "customer writes own messages" ON public.ss_chat_messages FOR INSERT TO authenticated WITH CHECK (((author_kind = 'customer'::text) AND (EXISTS ( SELECT 1 FROM public.ss_chat_channels c WHERE ((c.id = ss_chat_messages.channel_id) AND (c.kind = 'customer'::text) AND (c.customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)))))))$q$,
$q$CREATE POLICY "customers add own payment proofs" ON public.ss_payment_proofs FOR INSERT TO authenticated WITH CHECK ((customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)))$q$,
$q$CREATE POLICY "customers read own check payments" ON public.ss_check_payments FOR SELECT TO authenticated USING ((customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)))$q$,
$q$CREATE POLICY "customers read own payment proofs" ON public.ss_payment_proofs FOR SELECT TO authenticated USING ((customer_id IN ( SELECT public.ss_my_customer_ids() AS ss_my_customer_ids)))$q$,
$q$CREATE POLICY "finance can read bank details" ON public.ss_bank_details FOR SELECT TO authenticated USING (public.ss_can_finance())$q$,
$q$CREATE POLICY "finance can update bank details" ON public.ss_bank_details FOR UPDATE TO authenticated USING (public.ss_can_finance()) WITH CHECK (public.ss_can_finance())$q$,
$q$CREATE POLICY "finance can write bank details" ON public.ss_bank_details FOR INSERT TO authenticated WITH CHECK (public.ss_can_finance())$q$,
$q$CREATE POLICY "finance manages check payments" ON public.ss_check_payments TO authenticated USING (public.ss_can_finance()) WITH CHECK (public.ss_can_finance())$q$,
$q$CREATE POLICY "finance reads payment proofs" ON public.ss_payment_proofs FOR SELECT TO authenticated USING (public.ss_can_finance())$q$,
$q$CREATE POLICY "office delete internal notes" ON public.ss_internal_notes FOR DELETE TO authenticated USING (public.ss_is_office())$q$,
$q$CREATE POLICY "office delete internal tasks" ON public.ss_internal_tasks FOR DELETE TO authenticated USING (public.ss_is_office())$q$,
$q$CREATE POLICY "office manages crew hours" ON public.ss_staff_availability TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "office manages email attachments" ON public.ss_email_attachments TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "office manages email messages" ON public.ss_email_messages TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "office manages email threads" ON public.ss_email_threads TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "office manages time off" ON public.ss_staff_time_off TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "office manages vendors" ON public.ss_vendors TO authenticated USING (public.ss_is_office()) WITH CHECK (public.ss_is_office())$q$,
$q$CREATE POLICY "office reads attempts" ON public.ss_access_attempts FOR SELECT TO authenticated USING (public.ss_is_office())$q$,
$q$CREATE POLICY "office reads pricing settings" ON public.ss_pricing_settings FOR SELECT TO authenticated USING (public.ss_is_office())$q$,
$q$CREATE POLICY "office reads push subscriptions" ON public.ss_push_subscriptions FOR SELECT TO authenticated USING (public.ss_is_office())$q$
  ]
  LOOP
    BEGIN
      EXECUTE s;
    EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN
      NULL;
    END;
  END LOOP;
END
$mig$;